export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
export const FILTER_PRODUCTS_BY_SEARCH = "FILTER_PRODUCTS_BY_SEARCH";

// cart action handler
export const ADD_TO_CART = "ADD_TO_CART";
export const ING_CARD_PROD_PRICE = "ING_CARD_PROD_PRICE";
